# This file is a template, and might need editing before it works on your project.
# This file is a template, and might need editing before it works on your project.
image: python:latest

before_script:
  - python -V                                   # Print out python version for debugging

